name: advanced_ntp
description: Fetch accurate time or current DateTime object from (NTP) Network Time Protocol server.
version: 1.0.0
homepage: https://github.com/elgill/advanced_ntp

environment:
  sdk: '>=2.12.0-0 <3.0.0'
